### ISSUE TITLE
Entrevistas a voluntarios de la comunidad

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/meta#1]
## Objetivo:

Entrevistas voluntarios claves de la comunidad para recopilar su visión y objetivos de la comunidad.
## Éxito:
- Al menos el 90% de los voluntarios tienen la entrevista
- Se documenta el 100% de las entrevistas con datos sobre visión y objetivos.
## Roles:

Coordinador: @nukeador @deimidis 
Involucrados: @bernimel @jusai @BoSicle @YunitoMH @cosmikspin @EnriqueV
## Requisitos:
- [x] Recopilar los horarios de los orientadores (@nukeador @deimidis, [fácil] 23 Nov)
- [x] Crear plantilla de correo (@nukeador @deimidis, [fácil] 23 Nov)
- [x] Correo a los voluntarios sobre el tema y pidiéndoles que comenten sus horarios. ([fácil] 23 Nov)
- [x] Portal a la hoja de voluntarios los horarios (todos [medio] 30 Nov)
- [x] Asignar los horarios de los voluntarios a los orientadores (todos [medio] 30 Nov)
- [x] Orientadores contactan con sus voluntarios asignados y fijan día/hora entrevista (todos [medio] 30 Nov)
- [ ] Entrevistas realizadas (todos [dificil] 18 Dic)

**Comment by deimidis** [comment]
¿En qué estado estamos en el punto 2 que debería terminarse hoy?

**Comment by nukeador** [comment]
Solo dos personas han indicado sus horarios

https://public.etherpad-mozilla.org/p/mozhispano-horarios-orientadores

**Comment by nukeador** [comment]
Actualicé las tareas porque evidentemente primero necesitamos los horarios de los orientadores, luego enviar el correo a voluntarios y luego ver a quién se le asigna quien basado en los horarios.

**Comment by nukeador** [comment]
Correo enviado a los 41 voluntarios en la lista

**Comment by nukeador** [comment]
Hemos empezado a apuntar horarios de la gente en la lista.

@bernimel @jusai @BoSicle @YunitoMH @cosmikspin @EnriqueV ¿podéis ir mirando si ya hay alguno en vuestros horarios y os les asignáis poniendo vuestro nombre en la columna "Orientador"?

https://docs.google.com/spreadsheets/d/1y1eUXf3PeGsBAXGri3WkPxBv2wJ9wN4JMz759Q_jiTk/edit#gid=0

Y si ya les escribís o mandáis un calendar invite, genial para ahorrar tiempo :D

¡Gracias!

**Comment by siclemx** [comment]
Todos son horarios UTC, correcto?

**Comment by nukeador** [comment]
Sí

**Comment by nukeador** [comment]
Tenemos ya 14 personas en la hoja con sus horarios listos para fijar entrevista. Por favor asignaros gente durante los próximos días y contactar para fijar día.

Deberíamos tocar a unas 5 personas a entrevistar cada uno, así que no tengáis miedo en asignaros todos los que podáis ;)

**Comment by YunitoMH** [comment]
De acuerdo, Nuke, 

Yo por ahora ya me he asignado a cuatro personas y me estoy poniendo en contacto con ellas.

**Comment by nukeador** [comment]
Sólo 16 de las 41 personas contactadas han contestado. Posiblemente habría que mandar un recordatorio a los que no lo han hecho mañana.

Si ya habéis tenido alguna entrevista sería bueno comentario para ver qué tal fue todo y así todos aprenden :)

**Comment by nukeador** [comment]
Hasta el día 16 voy a estar un poco ausente, comentad si tenéis problemas para fijar las entrevistas y hacerlas :)

**Comment by EnriqueV** [comment]
Saludos yo ya tengo a 4 personas que ya estan acordadas las fechas para entrevista

**Comment by nukeador** [comment]
Recordad usar el documento plantilla para rellenarlo durante las entrevistas y guardarlo en la carpeta correspondiente :)

**Comment by nukeador** [comment]
@YunitoMH ¿En qué estado estamos ahora mismo? ¿Qué se necesita para empezar a unificar la información?

**Comment by nukeador** [comment]
Hola,

¡Podéis copiar las entrevistas a la carpeta de entrevistas para poder analizarlas?

https://drive.google.com/drive/u/1/folders/0B3CuegKgwkKkT0hyQVlmN00yeUU

¡Gracias!

**Comment by YunitoMH** [comment]
Si, claro!

Chicos, vamos un poco retrasados en esto y deberíamos empezar a ponernos las pilas.Se que ha habido fiestas, y por eso no nos hemos movido al ritmo que tocaría. 

He de reconocer que yo a causa de esto también he estado algo inactivo, pero año nuevo, metas nuevas así que... Me gustaria que pudierais subir las entrevistas realizadas, yo por mi parte voy a empezar a subir las mias ASAP.

Gracias.

**Comment by siclemx** [comment]
Yo por mi parte sigo en fiestas, hasta el 7 de Enero regreso a la ciudad y
ese día espero poder subir las entrevistas ya que no traigo conmigo mi
portátil :/

Saludos
Uriel

**Comment by nukeador** [comment]
Hola,

Esto se está demorando demasiado, tengo la sensación de porque queremos subir las entrevistas en un formato perfecto.

No necesitamos que el texto sea bonito ni perfecto, nadie va a leer estas entrevistas más que nosotros para luego sacar las ideas clave, por lo que por favor subidlas a la carpeta de entrevistas lo antes posible estén como estén (sería genial tenerlas para el lunes 11).

Una vez que las tengamos subidas simplemente es trabajar en leerlas para sacar las ideas clave con las cosas que quiere la gente de la comunidad.

Un saludo.

**Comment by YunitoMH** [comment]
Lo se y asumo plenamente la responsabilidad ya que debería haber sido yo el que hubiera movido más este tema. 

Por eso, ahora mismo acabo de subir todas las entrevistas realizadas y estoy intentando contactar con Uriel para que el también las suba y podamos llevar esto hacia delante ya que llevamos 1 mes de retraso respecto al plan inicial.

Saludos

**Comment by siclemx** [comment]
Hola! Ya eh subido casi todas las entrevistas que realicé solo me falta
una, que es la de Daas y esa si la estoy transcribiendo ya que fue por
audio/video y tengo algunas notas regadas en papel y bloc de notas, espero
poder terminarla para mañana mismo subirla.

Saludos
Uriel

**Comment by YunitoMH** [comment]
Hola, chicos:

Actualmente ya tenemos unas 15 entrevistas realizadas. Nuestro próximo paso sería que cada uno de nosotros resumiera los puntos principales de las entrevistas. Somos 6, por tanto cada uno debería resumir entre 2 o 3.

Agradecería mucho si cada uno, pudíera encontrar entre 30 min / 1 hora para llevarlo a cabo y así tenerlo listo para la semana que viene. 

Si teneis alguna duda, no dudéis en contactar conmigo por aqui o por Telegram y intentaré contestar lo más rápido posible. 

P.S: He creado un documento en la carpeta Entrevistas llamado "Resumen Entrevistas". Allí podemos ir poniendo los puntos principales de las entrevistas y así tenerlo todo unificado en un mismo sítio.

Saludos

**Comment by nukeador** [comment]
Nota: Queremos resumir los puntos en relación a los objetivos de la comunidad para poder luego hacer #2 juntando todos los puntos de vista.

Yo no voy a poder ayudar con esto hasta posiblemente el 27 de enero.

**Comment by nukeador** [comment]
No vamos a seguir realizando entrevistas, seguirmos en #2 con el proceso
