### ISSUE TITLE
Unificar metas y objetivos

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/meta#2]
## Objetivo:

Unificar en un documento la visión y las metas de la comunidad
## Éxito:
- Visión definida
- Al menos 4 metas definidas con sus objetivos
## Roles:

Coordinador: @nukeador @deimidis 
Involucrados: @bernimel @jusai @BoSicle @YunitoMH @cosmikspin @EnriqueV
## Requisitos:
- [x] Reunión para unificar datos (todos [medio] 18 Dic)
- [x] Documento con los objetivos creado ([medio] 21 Dic)
- [x] Reunión con coordinadores para definir subobjetivos ([dificil] 21 Dic)
- [x] Subobjetivos incorporados al documento ([medio] 21 Dic)

**Comment by nukeador** [comment]
Deberíamos reunirnos antes del jueves para hablar de esto. ¿Alguien no podría?

**Comment by siclemx** [comment]
Yo, si no es mañana Lunes, no podría hasta el domingo próximo.

Saludos
Uriel

**Comment by YunitoMH** [comment]
Yo creo que podría antes del jueves. Como te propuse Nukeador, creo que buenos dias para la reunión serian día 23, 27, 28, 29, 30. 

Saludos!

**Comment by nukeador** [comment]
Mañana a las 13:00UTC nos vamos a reunir @YunitoMH y yo para unificar estrategias. Si alguien se quiere unir que avise.

**Comment by nukeador** [comment]
Hola,

He creado un borrador con las metas y objetivos que sacamos @YunitoMH y yo en la reunión:

https://docs.google.com/spreadsheets/d/1aVKS06HO1GkpSxjsx5EunLXsdpZVzDDbpNvFwnPbtZc/edit#gid=1569936294

@bernimel @jusai @BoSicle @cosmikspin @EnriqueV por favor revisadlo lo antes posible porque vamos a llamar a reunión general de la comunidad para hablar de ellas.

**Comment by siclemx** [comment]
Una disculpa anduve algo ocupado con el trabajo y el regreso a la escuela, pero ya le di una leida :) ,  se edita algo o nos esperamos a la reunión?
